aeroportos = {
    'Tarauacá': {'Sigla': 'SBTK', 'Aeroporto': 'Tarauacá', 'Estado': 'AC'},
    'Presidente Médici': {'Sigla': 'SBRB', 'Aeroporto': 'Presidente Médici', 'Estado': 'AC'},
    'Internacional': {'Sigla': 'SBCZ', 'Aeroporto': 'Internacional', 'Estado': 'AC'},
    'Zumbi dos Palmares': {'Sigla': 'SBMO', 'Aeroporto': 'Zumbi dos Palmares', 'Estado': 'AL'},
    'Eduardo Gomes': {'Sigla': 'SBEG', 'Aeroporto': 'Eduardo Gomes', 'Estado': 'AM'},
    'Ponta Pelada': {'Sigla': 'SBMN', 'Aeroporto': 'Ponta Pelada', 'Estado': 'AM'},
    'Manicoré': {'Sigla': 'SBMY', 'Aeroporto': 'Manicoré', 'Estado': 'AM'},
    'Tabatinga': {'Sigla': 'SBTT', 'Aeroporto': 'Tabatinga', 'Estado': 'AM'},
    'Iuaretê': {'Sigla': 'SBYA', 'Aeroporto': 'Iuaretê', 'Estado': 'AM'},
    'São Gabriel da Cachoeira': {'Sigla': 'SBUA', 'Aeroporto': 'São Gabriel da Cachoeira', 'Estado': 'AM'},
    'Tefé': {'Sigla': 'SBTF', 'Aeroporto': 'Tefé', 'Estado': 'AM'},
    'Amapá': {'Sigla': 'SBAM', 'Aeroporto': 'Amapá', 'Estado': 'AP'},
    'Internacional AP': {'Sigla': 'SBMQ', 'Aeroporto': 'Internacional', 'Estado': 'AP'},
    'Oiapoque': {'Sigla': 'SBOI', 'Aeroporto': 'Oiapoque', 'Estado': 'AP'},
    'Bom Jesus da Lapa': {'Sigla': 'SBLP', 'Aeroporto': 'Bom Jesus da Lapa', 'Estado': 'BA'},
    'Caravelas': {'Sigla': 'SBCV', 'Aeroporto': 'Caravelas', 'Estado': 'BA'},
    'Jorge Amado': {'Sigla': 'SBIL', 'Aeroporto': 'Jorge Amado', 'Estado': 'BA'},
    'Chapada Diamantina': {'Sigla': 'SBLE', 'Aeroporto': 'Chapada Diamantina', 'Estado': 'BA'},
    'Paulo Afonso': {'Sigla': 'SBUF', 'Aeroporto': 'Paulo Afonso', 'Estado': 'BA'},
    'Porto Seguro': {'Sigla': 'SBPS', 'Aeroporto': 'Porto Seguro', 'Estado': 'BA'},
    'Dep. Luís Eduardo Magalhães': {'Sigla': 'SBSV', 'Aeroporto': 'Dep. Luís Eduardo Magalhães', 'Estado': 'BA'},
    'Vitória da Conquista': {'Sigla': 'SBQV', 'Aeroporto': 'Vitória da Conquista', 'Estado': 'BA'},
    'Pinto Martins': {'Sigla': 'SBFZ', 'Aeroporto': 'Pinto Martins', 'Estado': 'CE'},
    'Cariri': {'Sigla': 'SBJU', 'Aeroporto': 'Cariri', 'Estado': 'CE'},
    'Juscelino Kubitschek': {'Sigla': 'SBBR', 'Aeroporto': 'Juscelino Kubitschek', 'Estado': 'DF'},
    'Eurico Aguiar Salles': {'Sigla': 'SBVT', 'Aeroporto': 'Eurico Aguiar Salles', 'Estado': 'ES'},
    'Anápolis': {'Sigla': 'SBAN', 'Aeroporto': 'Anápolis', 'Estado': 'GO'},
    'Santa Genoveva': {'Sigla': 'SBGO', 'Aeroporto': 'Santa Genoveva', 'Estado': 'GO'},
    'Carolina': {'Sigla': 'SBCI', 'Aeroporto': 'Carolina', 'Estado': 'MA'},
    'Imperatriz': {'Sigla': 'SBIZ', 'Aeroporto': 'Imperatriz', 'Estado': 'MA'},
    'Mar. Cunha Machado': {'Sigla': 'SBSL', 'Aeroporto': 'Mar. Cunha Machado', 'Estado': 'MA'},
    'Araxá': {'Sigla': 'SBAX', 'Aeroporto': 'Araxá', 'Estado': 'MG'},
    'Carlos Prates': {'Sigla': 'SBPR', 'Aeroporto': 'Carlos Prates', 'Estado': 'MG'},
    'Barbacena': {'Sigla': 'SBBQ', 'Aeroporto': 'Barbacena', 'Estado': 'MG'},
    'Pampulha': {'Sigla': 'SBBH', 'Aeroporto': 'Pampulha', 'Estado': 'MG'},
    'Tancredo Neves': {'Sigla': 'SBCF', 'Aeroporto': 'Tancredo Neves', 'Estado': 'MG'},
    'Poços de Caldas': {'Sigla': 'SBPC', 'Aeroporto': 'Poços de Caldas', 'Estado': 'MG'},
    'Uberaba': {'Sigla': 'SBUR', 'Aeroporto': 'Uberaba', 'Estado': 'MG'},
    'Uberlândia': {'Sigla': 'SBUL', 'Aeroporto': 'Uberlândia', 'Estado': 'MG'},
    'Ipatinga': {'Sigla': 'SBIP', 'Aeroporto': 'Ipatinga', 'Estado': 'MG'},
    'Francisco de Assis': {'Sigla': 'SBJF', 'Aeroporto': 'Francisco de Assis', 'Estado': 'MG'},
    'Montes Claros': {'Sigla': 'SBMK', 'Aeroporto': 'Montes Claros', 'Estado': 'MG'},
    'Varginha': {'Sigla': 'SBVG', 'Aeroporto': 'Varginha', 'Estado': 'MG'},
    'Gov. Valadares': {'Sigla': 'SBGV', 'Aeroporto': 'Gov. Valadares', 'Estado': 'MG'},
    'Internacional': {'Sigla': 'SBCG', 'Aeroporto': 'Internacional', 'Estado': 'MS'},
    'Corumbá': {'Sigla': 'SBCR', 'Aeroporto': 'Corumbá', 'Estado': 'MS'},
    'Internacional MS': {'Sigla': 'SBPP', 'Aeroporto': 'Internacional', 'Estado': 'MS'},
    'Alta Floresta': {'Sigla': 'SBAT', 'Aeroporto': 'Alta Floresta', 'Estado': 'MT'},
    'Barra do Garças': {'Sigla': 'SBBW', 'Aeroporto': 'Barra do Garças', 'Estado': 'MT'},
    'Marechal Rondon': {'Sigla': 'SBCY', 'Aeroporto': 'Marechal Rondon', 'Estado': 'MT'},
    'Altamira': {'Sigla': 'SBHT', 'Aeroporto': 'Altamira', 'Estado': 'PA'},
    'Val-de-Cans': {'Sigla': 'SBBE', 'Aeroporto': 'Val-de-Cans', 'Estado': 'PA'},
    'Itaituba': {'Sigla': 'SBIH', 'Aeroporto': 'Itaituba', 'Estado': 'PA'},
    'Jacareacanga': {'Sigla': 'SBEK', 'Aeroporto': 'Jacareacanga', 'Estado': 'PA'},
    'Marabá': {'Sigla': 'SBMA', 'Aeroporto': 'Marabá', 'Estado': 'PA'},
    'Cachimbó': {'Sigla': 'SBCC', 'Aeroporto': 'Cachimbó', 'Estado': 'PA'},
    'Trombetas': {'Sigla': 'SBTB', 'Aeroporto': 'Trombetas', 'Estado': 'PA'},
    'Carajás': {'Sigla': 'SBCJ', 'Aeroporto': 'Carajás', 'Estado': 'PA'},
    'Santarém': {'Sigla': 'SBSN', 'Aeroporto': 'Santarém', 'Estado': 'PA'},
    'Tucuruí': {'Sigla': 'SBTU', 'Aeroporto': 'Tucuruí', 'Estado': 'PA'},
    'Conceição do Araguaia': {'Sigla': 'SBAA', 'Aeroporto': 'Conceição do Araguaia', 'Estado': 'PA'},
    'Pres. João Suassuna': {'Sigla': 'SBKG', 'Aeroporto': 'Pres. João Suassuna', 'Estado': 'PB'},
    'Pres. Castro Pinto': {'Sigla': 'SBJP', 'Aeroporto': 'Pres. Castro Pinto', 'Estado': 'PB'},
    'Fernando de Noronha': {'Sigla': 'SBFN', 'Aeroporto': 'Fernando de Noronha', 'Estado': 'PE'},
    'Guararapes': {'Sigla': 'SBRF', 'Aeroporto': 'Guararapes', 'Estado': 'PE'},
    'Sen. Nilo Coelho': {'Sigla': 'SBPL', 'Aeroporto': 'Sen. Nilo Coelho', 'Estado': 'PE'},
    'Dr. João Silva Filho': {'Sigla': 'SBPB', 'Aeroporto': 'Dr. João Silva Filho', 'Estado': 'PI'},
    'Sen. Petrônio Portella': {'Sigla': 'SBTE', 'Aeroporto': 'Sen. Petrônio Portella', 'Estado': 'PI'},
    'Londrina': {'Sigla': 'SBLO', 'Aeroporto': 'Londrina', 'Estado': 'PR'},
    'Cataratas': {'Sigla': 'SBFI', 'Aeroporto': 'Cataratas', 'Estado': 'PR'},
    'Bacacheri': {'Sigla': 'SBBI', 'Aeroporto': 'Bacacheri', 'Estado': 'PR'},
    'Afonso Pena': {'Sigla': 'SBCT', 'Aeroporto': 'Afonso Pena', 'Estado': 'PR'},
    'Silvio Name Junior': {'Sigla': 'SBMG', 'Aeroporto': 'Silvio Name Junior', 'Estado': 'PR'},
    'Cabo Frio': {'Sigla': 'SBCB', 'Aeroporto': 'Cabo Frio', 'Estado': 'RJ'},
    'Afonsos': {'Sigla': 'SBAF', 'Aeroporto': 'Afonsos', 'Estado': 'RJ'},
    'Galeão': {'Sigla': 'SBGL', 'Aeroporto': 'Galeão', 'Estado': 'RJ'},
    'Jacarepaguá': {'Sigla': 'SBJR', 'Aeroporto': 'Jacarepaguá', 'Estado': 'RJ'},
    'Santos Dumont': {'Sigla': 'SBRJ', 'Aeroporto': 'Santos Dumont', 'Estado': 'RJ'},
    'Santa Cruz': {'Sigla': 'SBSC', 'Aeroporto': 'Santa Cruz', 'Estado': 'RJ'},
    'Macaé': {'Sigla': 'SBME', 'Aeroporto': 'Macaé', 'Estado': 'RJ'},
    'S. Pedro da Aldeia': {'Sigla': 'SBES', 'Aeroporto': 'S. Pedro da Aldeia', 'Estado': 'RJ'},
    'Bartolomeu Lysandro': {'Sigla': 'SBCP', 'Aeroporto': 'Bartolomeu Lysandro', 'Estado': 'RJ'},
    'Dix-Sept Rosado': {'Sigla': 'SBMS', 'Aeroporto': 'Dix-Sept Rosado', 'Estado': 'RN'},
    'Augusto Severo': {'Sigla': 'SBNT', 'Aeroporto': 'Augusto Severo', 'Estado': 'RN'},
    'Guajará Mirim': {'Sigla': 'SBGM', 'Aeroporto': 'Guajará Mirim', 'Estado': 'RO'},
    'Brigadeiro Camarão': {'Sigla': 'SBVH', 'Aeroporto': 'Brigadeiro Camarão', 'Estado': 'RO'},
    'Gov. Jorge Teixeira de Oliveira': {'Sigla': 'SBPV', 'Aeroporto': 'Gov. Jorge Teixeira de Oliveira', 'Estado': 'RO'},
    'Boa Vista': {'Sigla': 'SBBV', 'Aeroporto': 'Boa Vista', 'Estado': 'RR'},
    'Bagé': {'Sigla': 'SBBG', 'Aeroporto': 'Bagé', 'Estado': 'RS'},
    'Santa Maria': {'Sigla': 'SBSM', 'Aeroporto': 'Santa Maria', 'Estado': 'RS'},
    'Salgado Filho': {'Sigla': 'SBPA', 'Aeroporto': 'Salgado Filho', 'Estado': 'RS'},
    'Pelotas': {'Sigla': 'SBPK', 'Aeroporto': 'Pelotas', 'Estado': 'RS'},
    'Canoas': {'Sigla': 'SBCO', 'Aeroporto': 'Canoas', 'Estado': 'RS'},
    'Rubem Berta': {'Sigla': 'SBUG', 'Aeroporto': 'Rubem Berta', 'Estado': 'RS'},
    'Chapecó': {'Sigla': 'SBCH', 'Aeroporto': 'Chapecó', 'Estado': 'SC'},
    'Forquilinha': {'Sigla': 'SBCM', 'Aeroporto': 'Forquilinha', 'Estado': 'SC'},
    'Hercílio Luz': {'Sigla': 'SBFL', 'Aeroporto': 'Hercílio Luz', 'Estado': 'SC'},
    'Lauro Carneiro de Loyola': {'Sigla': 'SBJV', 'Aeroporto': 'Lauro Carneiro de Loyola', 'Estado': 'SC'},
    'Min. Victor Konder': {'Sigla': 'SBNF', 'Aeroporto': 'Min. Victor Konder', 'Estado': 'SC'},
    'Santa Maria': {'Sigla': 'SBAR', 'Aeroporto': 'Santa Maria', 'Estado': 'SE'},
    'Araçatuba': {'Sigla': 'SBAU', 'Aeroporto': 'Araçatuba', 'Estado': 'SP'},
    'Bauru': {'Sigla': 'SBBU', 'Aeroporto': 'Bauru', 'Estado': 'SP'},
    'Viracopos': {'Sigla': 'SBKP', 'Aeroporto': 'Viracopos', 'Estado': 'SP'},
    'Pres. Prudente': {'Sigla': 'SBDN', 'Aeroporto': 'Pres. Prudente', 'Estado': 'SP'},
    'Leite Lopes': {'Sigla': 'SBRP', 'Aeroporto': 'Leite Lopes', 'Estado': 'SP'},
    'S. J. do Rio Preto': {'Sigla': 'SBSR', 'Aeroporto': 'S. J. do Rio Preto', 'Estado': 'SP'},
    'Fontenelle': {'Sigla': 'SBYS', 'Aeroporto': 'Fontenelle', 'Estado': 'SP'},
    'Base Aérea': {'Sigla': 'SBST', 'Aeroporto': 'Base Aérea', 'Estado': 'SP'},
    'Gavião Peixoto': {'Sigla': 'SBGP', 'Aeroporto': 'Gavião Peixoto', 'Estado': 'SP'},
    'Guaratinguetá': {'Sigla': 'SBGW', 'Aeroporto': 'Guaratinguetá', 'Estado': 'SP'},
    'Guarulhos': {'Sigla': 'SBGR', 'Aeroporto': 'Guarulhos', 'Estado': 'SP'},
    'São J. dos Campos': {'Sigla': 'SBSJ', 'Aeroporto': 'São J. dos Campos', 'Estado': 'SP'},
    'Campo de Marte': {'Sigla': 'SBMT', 'Aeroporto': 'Campo de Marte', 'Estado': 'SP'},
    'Congonhas': {'Sigla': 'SBSP', 'Aeroporto': 'Congonhas', 'Estado': 'SP'},
    'Taubaté': {'Sigla': 'SBTA', 'Aeroporto': 'Taubaté', 'Estado': 'SP'},
    'Palmas': {'Sigla': 'SBPJ', 'Aeroporto': 'Palmas', 'Estado': 'TO'},
    'Porto Nacional': {'Sigla': 'SBPN', 'Aeroporto': 'Porto Nacional', 'Estado': 'TO'}
}
